---
title: "Relatório de Partida"
subtitle: "Argentina vs Arábia Saudita, Copa do Mundo de 2022"
author: "Leonardo Damiani"
output: 
  html_document:
    toc: true          # Adiciona a navegação com sumário
    toc_float: true    # Deixa o sumário flutuante na página
    toc_depth: 4       # Profundidade de níveis no sumário (h1 e h2)
    number_sections: false # Numera as seções
    theme: journal    # Tema de cores do documento
    highlight: tango   # Estilo de destaque de código
    df_print: kable    # Formata os dataframes com kable no HTML
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
library(kableExtra)
library(SBpitch) # ggplot2
library(StatsBombR)
library(tidyverse)
library(dplyr)
library(purrr)
library(grid)
library(gridExtra)
library(soccermatics)
library(extrafont) 
library(ggupset)
library(tibbletime)
library(ggtext)
library(ggrepel)
library(glue)
library(patchwork)
library(cowplot)
library(gtable)
library(magick)
library(ggtext)
source("pitch.R")
```

<br>
<br>

## Dados da Partida

<br>

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='hide'}

# ----------- Get Match Data --------- #
matches <- FreeCompetitions()  %>% 
  filter(competition_id==43, season_name == 2022) %>% 
  FreeMatches() %>% filter(match_id == 3857300) 

# Events e Lineups
events <- matches %>% get.matchFree()
lineups <- matches %>% get.lineupsFree()

```
<br>

## Visualização Geral da Partida

<br>

```{r, echo=FALSE, warning=FALSE, message=FALSE}

# Data
data_brasileira <- as.Date(matches$match_date[1], format = "%Y-%m-%d")
data_formatada <- format(data_brasileira, "%d/%m/%Y") # Formato dia/mês/ano

# Horário
horario_brasileiro <- as.POSIXct(matches$kick_off[1], format = "%H:%M:%OS", tz = "America/Sao_Paulo")
horario_formatado <- format(horario_brasileiro, "%H:%M:%S")

c1 = c(matches$competition.competition_name,
       matches$competition_stage.name,
       matches$match_week,
       data_formatada,
       horario_formatado,
       matches$stadium.name,
       matches$referee.name)
c2 = c('Competição', 'Fase', 'Rodada', 'Data', 'Horário', 'Estádio', 'Árbitro')
  
infos = data.frame('Variáveis' = c2, 'Informações' = c1)
titulo = "<span style='font-size: 20px; font-weight: bold;  text-align: center;'><span style='color: blue;'>Argentina </span><span style='color: blue;'>[1]</span> x <span style='color: green;'>[2]</span> <span style='color: green;'>Árabia Saudita</span></span>"

# Tabela
tabela_kable <- kable(infos, 
                     caption = titulo,
                     format = "html",
                     digits = 2, align = 'c') 

# Adicionar estilos com kableExtra
tabela_kable <- tabela_kable %>%
  kable_styling("striped", full_width = F) %>%
  column_spec(1, width = "4cm") %>%  # Definindo largura da coluna "Variáveis"
  column_spec(2, width = "6cm") %>%  # Definindo largura da coluna "Informações"
  kable_styling(position = "center")  # Centralizando a tabela

# Exibir a tabela
tabela_kable
```


<br>

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.align='center', fig.width=10}
# ----------- Lineups --------- #

# Definir as posições no campo (x, y) e rótulos das posições táticas
positions <- data.frame(
  
  id = seq(1, 25),
  
  label = c("GK", "RB", "RCB", "CB", "LCB", "LB",
            "RWB", "LWB", "RDM", "CDM", "LDM",
            "RM", "RCM", "CM", "LCM", "LM",
            "RW", "RAM", "CAM", "LAM", "LW",
            "RCF", "ST", "LCF", "SS"),
  
  x = c(9, 30, 22, 30, 22, 30, 
        47, 47, 47, 47, 47, 
        75, 75, 75, 65, 75, 
        80, 80, 80, 80, 80, 
        95, 95, 95, 110),
  
  y = c(40, 70, 55, 40, 25, 10,
        70, 10, 55, 40, 25, 
        70, 10, 55, 40, 25, 
        70, 10, 55, 40, 25, 
        55, 40, 25, 40)
)

# Argentina
lineup_arg = lineups$lineup[[1]]
todo_nome = c()
players_arg = c()
positions_arg = c()
id_reserva = c()
for (i in 1:nrow(lineup_arg)){
  
 aux = lineup_arg$positions[[i]]
 if (length(aux) == 0){
   next
 } else {
   todo_nome = append(todo_nome, lineup_arg$player_name[i])
   if (is.na(lineup_arg$player_nickname[i])){
     players_arg = append(players_arg, lineup_arg$player_name[i])
   } else{
     players_arg = append(players_arg, paste(strsplit(lineup_arg$player_nickname[i], " ")[[1]][-1], collapse = " "))}
   positions_arg = append(positions_arg, aux$position_id[1])
   if (aux$from[1] != "00:00"){
     id_reserva = append(id_reserva, 1)
   } else {
     id_reserva = append(id_reserva, 0)
   }
}
}
lineup1 = data.frame(nome = todo_nome, player = players_arg, id = positions_arg, reserva = id_reserva) %>%
  left_join(positions)

# Criar o campo de futebol e adicionar as posições
arg_lineup_plot = create_StatsBomb_Pitch_Vertical(
  grass_colour = "#538032", 
  line_colour =  "#ffffff", 
  background_colour = "#538032", 
  goal_colour = "#000000"
) + # Gira o campo para formato vertical
  geom_text(data = lineup1[lineup1$reserva!=1,], aes(x = y, y = x, label = player), 
            size = 4, 
            color = "lightblue") + # Adicionar as posições
  ggtitle("Argentina")  +
  coord_fixed(ratio = 70/100) 


# Saudita
lineup_sau = lineups$lineup[[2]]
todo_nome = c()
players_sau = c()
positions_sau = c()
id_reserva = c()
for (i in 1:nrow(lineup_sau)){
  
  aux = lineup_sau$positions[[i]]
  if (length(aux) == 0){
    next
  } else {
    todo_nome = append(todo_nome, lineup_sau$player_name[i])
    if (is.na(lineup_sau$player_nickname[i])){
      players_sau = append(players_sau, lineup_sau$player_name[i])
    } else{
      players_sau = append(players_sau, paste(strsplit(lineup_sau$player_nickname[i], " ")[[1]][-1], collapse = " "))}
    positions_sau = append(positions_sau, aux$position_id[1])
    if (aux$from[1] != "00:00"){
      id_reserva = append(id_reserva, 1)
    } else {
      id_reserva = append(id_reserva, 0)
    }
  }
}
lineup2 = data.frame(nome = todo_nome, player = players_sau, id = positions_sau, reserva = id_reserva) %>%
  left_join(positions)

# Criar o campo de futebol e adicionar as posições
sau_lineup_plot = create_StatsBomb_Pitch_Vertical(
  grass_colour = "#538032", 
  line_colour =  "#ffffff", 
  background_colour = "#538032", 
  goal_colour = "#000000"
) + # Gira o campo para formato vertical
  geom_text(data = lineup2[lineup2$reserva!=1,], aes(x = y, y = x, label = player), 
            size = 4, 
            color = "lightgreen") + # Adicionar as posições
  ggtitle("Arábia Saudita")  +
  coord_fixed(ratio = 70/100) 

# Escalações
grid.arrange(arg_lineup_plot,
             grid::textGrob(" "), # Espaço em branco
             sau_lineup_plot, 
             ncol = 3, 
             widths = c(1, 0.1, 1)) # Ajusta os tamanhos das colunas
```
<br>

```{r, echo=FALSE, warning=FALSE, message=FALSE}
events = events %>%
  ## player name
  mutate(player.name = case_when(
    player.name == "Ángel Fabián Di María Hernández" ~ "Di María",
    player.name == "Nicolás Hernán Otamendi" ~ "Otamendi",
    player.name == "Lionel Andrés Messi Cuccittini" ~ "Messi",
    player.name == "Nicolás Alejandro Tagliafico" ~ "Tagliafico",
    player.name == "Damián Emiliano Martínez" ~ "E. Martínez",
    player.name == "Alejandro Darío Gómez" ~ "Papu Gómez",
    player.name == "Rodrigo Javier De Paul" ~ "De Paul",
    player.name == "Lautaro Javier Martínez" ~ "L. Martínez",
    player.name == "Leandro Daniel Paredes" ~ "Paredes",
    player.name == "Marcos Javier Acuña" ~ "Acuña",
    player.name == "Lisandro Martínez" ~ "Lisandro Martínez",
    player.name == "Nahuel Molina Lucero" ~ "Molina",
    player.name == "Julián Álvarez" ~ "Julián Álvarez",
    player.name == "Enzo Fernandez" ~ "Enzo Fernandez",
    player.name == "Salman Mohammed Al Faraj" ~ "Al Faraj",
    player.name == "Yasir Gharsan Al Shahrani" ~ "Al Shahrani",
    player.name == "Salem Mohammed Al Dawsari" ~ "Al Dawsari",
    player.name == "Mohammed Al Burayk" ~ "Al Burayk",
    player.name == "Mohammed Kanoo" ~ "Kanoo",
    player.name == "Mohammed Khalil Al Owais" ~ "Al Owais",
    player.name == "Ali Albulayhi" ~ "Ali Albulayhi",
    player.name == "Abdulelah Al Amri" ~ "Al Amri",
    player.name == "Firas Tariq Nasser Al Albirakan" ~ "Albirakan",
    player.name == "Saleh Khalid Al Shehri" ~ "Al Shehri",
    player.name == "Hassan Mohammed Al-Tambakti" ~ "Al-Tambakti",
    player.name == "Saud Abdullah Abdul Hamid" ~ "Abdul Hamid",
    player.name == "Nawaf Shaker Al Abid" ~ "Al Abid",
    player.name == "Abdulelah Saad Hameed Al-Malki" ~ "Al-Malki",
    player.name == "Sultan Abdullah Salim Al Ghannam" ~ "Al Ghannam",
    player.name == "Haitham Mohammed Asiri" ~ "Asiri",
    TRUE ~ player.name
  )) %>% 
  ## pass.recipient.name
  mutate(pass.recipient.name = case_when(
    pass.recipient.name == "Ángel Fabián Di María Hernández" ~ "Di María",
    pass.recipient.name == "Nicolás Hernán Otamendi" ~ "Otamendi",
    pass.recipient.name == "Lionel Andrés Messi Cuccittini" ~ "Messi",
    pass.recipient.name == "Nicolás Alejandro Tagliafico" ~ "Tagliafico",
    pass.recipient.name == "Damián Emiliano Martínez" ~ "E. Martínez",
    pass.recipient.name == "Alejandro Darío Gómez" ~ "Papu Gómez",
    pass.recipient.name == "Rodrigo Javier De Paul" ~ "De Paul",
    pass.recipient.name == "Lautaro Javier Martínez" ~ "L. Martínez",
    pass.recipient.name == "Leandro Daniel Paredes" ~ "Paredes",
    pass.recipient.name == "Marcos Javier Acuña" ~ "Acuña",
    pass.recipient.name == "Lisandro Martínez" ~ "Lisandro Martínez",
    pass.recipient.name == "Nahuel Molina Lucero" ~ "Molina",
    pass.recipient.name == "Julián Álvarez" ~ "Julián Álvarez",
    pass.recipient.name == "Enzo Fernandez" ~ "Enzo Fernandez",
    pass.recipient.name == "Salman Mohammed Al Faraj" ~ "Al Faraj",
    pass.recipient.name == "Yasir Gharsan Al Shahrani" ~ "Al Shahrani",
    pass.recipient.name == "Salem Mohammed Al Dawsari" ~ "Al Dawsari",
    pass.recipient.name == "Mohammed Al Burayk" ~ "Al Burayk",
    pass.recipient.name == "Mohammed Kanoo" ~ "Kanoo",
    pass.recipient.name == "Mohammed Khalil Al Owais" ~ "Al Owais",
    pass.recipient.name == "Ali Albulayhi" ~ "Ali Albulayhi",
    pass.recipient.name == "Abdulelah Al Amri" ~ "Al Amri",
    pass.recipient.name == "Firas Tariq Nasser Al Albirakan" ~ "Albirakan",
    pass.recipient.name == "Saleh Khalid Al Shehri" ~ "Al Shehri",
    pass.recipient.name == "Hassan Mohammed Al-Tambakti" ~ "Al-Tambakti",
    pass.recipient.name == "Saud Abdullah Abdul Hamid" ~ "Abdul Hamid",
    pass.recipient.name == "Nawaf Shaker Al Abid" ~ "Al Abid",
    pass.recipient.name == "Abdulelah Saad Hameed Al-Malki" ~ "Al-Malki",
    pass.recipient.name == "Sultan Abdullah Salim Al Ghannam" ~ "Al Ghannam",
    pass.recipient.name == "Haitham Mohammed Asiri" ~ "Asiri",
    TRUE ~ pass.recipient.name
  ))
```


<br>

```{r, echo=FALSE, warning=FALSE, message=FALSE}

# Total xG Match
match_xg_total <- events %>% 
  mutate(shot.statsbomb_xg = if_else(is.na(shot.statsbomb_xg), 0, shot.statsbomb_xg)) %>%
  group_by(team.name) %>% 
  summarize(tot_xg = sum(shot.statsbomb_xg) %>% signif(digits = 2)) %>% 
  mutate(team_label = glue::glue("{team.name}: {tot_xg} xG"))

match_xg <- events %>% 
  mutate(shot.statsbomb_xg = if_else(is.na(shot.statsbomb_xg), 0, shot.statsbomb_xg)) %>% 
  left_join(match_xg_total, by = "team.name") %>% 
  mutate(player_label = case_when(
    shot.outcome.name == "Goal" ~ glue("{player.name}: {shot.statsbomb_xg %>% signif(digits = 2)} xG"), TRUE ~ ""))

# Shot xG Sum
match_rollsum <- match_xg %>% 
  group_by(minute, team.name, period) %>% 
  summarize(sumxg = sum(shot.statsbomb_xg)) %>% 
  ungroup() %>% 
  group_by(team.name) %>% 
  mutate(rollsum = lag(cumsum(sumxg)),
         rollsum = if_else(is.na(rollsum), 0, rollsum)) %>% 
  select(team.name, minute, rollsum, sumxg) %>%
  mutate(rollsum = case_when(
    row_number() == n() & sumxg != 0 ~ rollsum + sumxg,
    TRUE ~ rollsum
  ))

# Goals + Players Info
match_rollsum_goals <- match_rollsum %>% 
  left_join(match_xg %>% filter(shot.outcome.name == "Goal") %>% 
              select(minute, shot.outcome.name, team.name, player.name), by = c("minute", "team.name")) %>% 
  mutate(rollsum_goal = rollsum + sumxg,
         minute_goal = minute + 1,
         player_label = case_when(
           shot.outcome.name == "Goal" ~ glue::glue("{player.name}: {sumxg %>% signif(digits = 2)} xG"),
           TRUE ~ ""))

# Exclui linha errada
i = which(match_rollsum_goals$player_label == "Al Shehri: 0 xG")
match_rollsum_goals = match_rollsum_goals[-i,]

```

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.align='center', fig.height=5}

# Plot xG Acumlado
tot_match_df <- match_xg %>% 
  pull(tot_xg)

match_rollsum_goals_plot <- match_rollsum_goals %>% 
  ggplot(aes(x = minute, y = rollsum, 
             group = team.name, color = team.name)) +
  geom_line(linewidth = 2.5) +
  geom_label_repel(data = match_rollsum_goals %>% filter(shot.outcome.name == "Goal"),
             aes(x = minute_goal, y = rollsum_goal, 
                 color = team.name, label = player_label), 
             nudge_x = 2, nudge_y = 0.25, family = "Source Sans Pro",
             show.legend = FALSE) +
  geom_point(data = match_rollsum_goals %>% filter(shot.outcome.name == "Goal"),
             aes(x = minute_goal, y = rollsum_goal, color = team.name), show.legend = FALSE,
             size = 3, shape = 21, fill = "white", stroke = 1.25)  +
  scale_color_manual(values = c("Argentina" = "#00CED1",
                                "Saudi Arabia" = "#006400"),
                     labels = c("Argentina", "Árabia Saudita")) +
  scale_fill_manual(values = c("Argentina" = "#00CED1",
                               "Saudi Arabia" = "#006400")) +
  scale_x_continuous(breaks = c(seq(0, 90, by = 5), 104),
                     labels = c(seq(0, 40, by = 5), "HT", 
                                seq(50, 90, by = 5), "FT"),
                     expand = c(0.01, 0),
                     limits = c(0, 104))  +
  scale_y_continuous(sec.axis = sec_axis(~ ., breaks = c(0.15, 2.5))) +
  labs(title = "Gols Esperados ao Longo da Partida",
       x = NULL,
       y = "Gols Esperados") +
  theme_minimal() +
  theme(text = element_text(family = "Source Sans Pro"),
        plot.title = element_markdown(size = 20, family = "Source Sans Pro"),
        axis.title = element_text(size = 12, color = "grey20"),
        axis.text = element_text(size = 8, face = "bold"),
        panel.grid.minor = element_blank(),
        legend.text = element_markdown(size = 14),
        legend.position = c(0.3, 0.95),
        legend.direction = "horizontal",
        legend.title = element_blank())

match_rollsum_goals_plot
```


<br>
<br>

## Ações Com Bola

<br>

### Chutes

<br>

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.height=5}

# ----------- XG e XGA --------- #

# xGA
xGA = events %>%
  filter(type.name=="Shot") %>%
  select(shot.key_pass_id, xGA = shot.statsbomb_xg) 

# Shots Assists
shot_assists = left_join(events, xGA, by = c("id" = "shot.key_pass_id")) %>%
  select(team.name, player.name, player.id, type.name, pass.shot_assist,
         pass.goal_assist, xGA ) %>% #4
  filter(pass.shot_assist==TRUE | pass.goal_assist==TRUE) #5

# Player xGA
player_xGA = shot_assists %>%
  group_by(player.name, player.id, team.name) %>%
  summarise(xGA = sum(xGA, na.rm = TRUE))

# Player xG - Without Penalty
player_xG_xGA = events %>%
  filter(type.name=="Shot") %>%
  filter(shot.type.name != "Penalty" | is.na(shot.type.name)) %>%
  group_by(player.name, player.id, team.name) %>%
  summarise(xG = sum(shot.statsbomb_xg, na.rm = TRUE)) %>%
  left_join(player_xGA) %>%
  mutate(
    xGA = replace_na(xGA, 0),
    xG_xGA = sum(xG+xGA, na.rm =TRUE)) %>%
  arrange(desc(xG_xGA))

# Chart Data
chart = player_xG_xGA %>%
  ungroup() %>%
  select(-c(team.name, player.id)) %>%
  pivot_longer(-player.name, names_to = "variable", values_to = "value") %>%
  filter(variable =="xG" | variable=="xGA") %>%
  mutate(value = replace(value, value == 0, NA),
         variable = factor(variable)) %>%
  drop_na() %>%
  left_join(player_xG_xGA[c('player.name', 'xG_xGA')])

# Chart
ggplot(chart, aes(x = reorder(player.name, xG_xGA), y = value, fill = variable)) +
  geom_bar(stat="identity", colour="white") +
  labs(title = "Expected Goal Contribution",
       x="", y="", caption ="NPxG = Value of shots taken (no penalties)\nxG assisted = Value of shots assisted")+
  theme(axis.text.y = element_text(size=10, color="#333333", family="Source Sans Pro"),
        axis.title = element_text(size=10, color="#333333", family="Source Sans Pro"),
        axis.text.x = element_text(size=10, color="#333333", family="Source Sans Pro"),
        axis.ticks = element_blank(),
        panel.background = element_rect(fill = "white", colour = "white"),
        plot.background = element_rect(fill = "white", colour ="white"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        plot.title=element_text(size=20, color="#333333", family="Source Sans Pro" , face="bold"),
        plot.caption=element_text(color="#333333", family="Source Sans Pro", size =10),
        text=element_text(family="Source Sans Pro"),
        legend.title=element_blank(),
        legend.text = element_text(size=12, color="#333333", family="Source Sans Pro"),
        legend.position = "bottom") + #2
  scale_fill_manual(values=c("#3371AC", "#DC2228"), labels = c("NPxG", "xG Assisted")) +
  scale_y_continuous(expand = c(0, 0), limits= c(0,max(chart$value) + 0.3)) + #4
  coord_flip()+ #5
  guides(fill = guide_legend(reverse = TRUE))

```

<br>

```{r, echo=FALSE, warning=FALSE, message = FALSE, fig.height=5}

# Chutes
shots_arg = events %>%
  mutate(location.x = map_dbl(location, 1, .default = NA),
         location.y = map_dbl(location, 2, .default = NA)) %>%
  filter(type.name=="Shot" & team.name == 'Argentina')

shots_sau = events %>%
  mutate(location.x = map_dbl(location, 1, .default = NA),
         location.y = map_dbl(location, 2, .default = NA)) %>%
  filter(type.name=="Shot" & team.name == 'Saudi Arabia')

# Chutes Colors
shotmapxgcolors <- c("#192780", "#2a5d9f", "#40a7d0", "#87cdcf", "#e7f8e6", "#f4ef95", "#FDE960", "#FCDC5F",
                     "#F5B94D", "#F0983E", "#ED8A37", "#E66424", "#D54F1B", "#DC2608", "#BF0000", "#7F0000", "#5F0000") #2
```

```{r, echo=FALSE, warning=FALSE, message = FALSE, fig.height=5}

# Chutes Argentina
shot_plot_arg = ggplot() +
  
  # Campo
  annotate("rect",xmin = 0, xmax = 120, ymin = 0, ymax = 80, fill = NA, colour = "black", size = 0.6) +
  annotate("rect",xmin = 0, xmax = 60, ymin = 0, ymax = 80, fill = NA, colour = "black", size = 0.6) +
  annotate("rect",xmin = 18, xmax = 0, ymin = 18, ymax = 62, fill = NA, colour = "black", size = 0.6) +
  annotate("rect",xmin = 102, xmax = 120, ymin = 18, ymax = 62, fill = NA, colour = "black", size = 0.6) +
  annotate("rect",xmin = 0, xmax = 6, ymin = 30, ymax = 50, fill = NA, colour = "black", size = 0.6) +
  annotate("rect",xmin = 120, xmax = 114, ymin = 30, ymax = 50, fill = NA, colour = "black", size = 0.6) +
  annotate("rect",xmin = 120, xmax = 120.5, ymin =36, ymax = 44, fill = NA, colour = "black", size = 0.6) +
  annotate("rect",xmin = 0, xmax = -0.5, ymin =36, ymax = 44, fill = NA, colour = "black", size = 0.6) +
  annotate("segment", x = 60, xend = 60, y = -0.5, yend = 80.5, colour = "black", size = 0.6)+
  annotate("segment", x = 0, xend = 0, y = 0, yend = 80, colour = "black", size = 0.6)+
  annotate("segment", x = 120, xend = 120, y = 0, yend = 80, colour = "black", size = 0.6)+
  theme(rect = element_blank(),
        line = element_blank()) +
  # add penalty spot right
  annotate("point", x = 108 , y = 40, colour = "black", size = 1.05) +
  annotate("path", colour = "black", size = 0.6,
           x=60+10*cos(seq(0,2*pi,length.out=2000)),
           y=40+10*sin(seq(0,2*pi,length.out=2000)))+
  # add centre spot
  annotate("point", x = 60 , y = 40, colour = "black", size = 1.05) +
  annotate("path", x=12+10*cos(seq(-0.3*pi,0.3*pi,length.out=30)), size = 0.6,
           y=40+10*sin(seq(-0.3*pi,0.3*pi,length.out=30)), col="black") +
  annotate("path", x=107.84-10*cos(seq(-0.3*pi,0.3*pi,length.out=30)), size = 0.6,
           y=40-10*sin(seq(-0.3*pi,0.3*pi,length.out=30)), col="black") +
  
  # Chutes
  geom_point(data = shots_arg, aes(x = location.x, y = location.y, fill = shot.statsbomb_xg, shape = shot.body_part.name),
             size = 6, alpha = 0.8) + #3

    # Tema
  theme(axis.text.x=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.caption=element_text(size=13,family="Source Sans Pro", hjust=0.5, vjust=0.5),
        plot.subtitle = element_text(size = 18, family="Source Sans Pro", hjust = 0.5),
        axis.text.y=element_blank(),
        legend.position = "top",
        legend.title=element_text(size=12,family="Source Sans Pro"),
        legend.text=element_text(size=11,family="Source Sans Pro"),
        legend.spacing.x = unit(0, 'cm'),  # Reduz o espaço entre as legendas
        legend.margin = margin(c(20, 5, -35, 30)),
        legend.key.size = unit(0.7, "cm"),
        plot.title = element_text(margin = margin(r = 10, b = 10), size = 18, family="Source Sans Pro", colour = "black", hjust = 0.5),
        legend.direction = "horizontal",
        axis.ticks=element_blank(),
        aspect.ratio = c(50/100),
        plot.background = element_rect(fill = "white"),
        strip.text.x = element_text(size=10, family="Source Sans Pro")) +
  labs(title = "Mapa de Chutes da Argentina") +
  scale_shape_manual(values = c("Head" = 21, "Right Foot" = 25, "Left Foot" = 24, "Other" = 23),
                     labels = c("Head" = "Cabeça", "Right Foot" = "Pé Direito", "Left Foot" = "Pé Esquerdo", "Other" = "Outro"), 
                     name ="") + 
  scale_fill_gradientn(colours = shotmapxgcolors, limit = c(0, 0.8), oob=scales::squish, name = "Gols Esperados") + 
  # Configuração das legendas (orientação e posicionamento)
  guides(fill = guide_colourbar(title.position = "top"),  # Escala de cores no topo
         shape = guide_legend(override.aes = list(size = 5, fill = "black"), 
                              title.position = "bottom")) +  # Formas embaixo
  coord_flip(xlim = c(80, 125)) #8

shot_plot_arg

```


```{r, echo=FALSE, warning=FALSE, message = FALSE, fig.height=5}

# Árabia
shot_plot_sau = ggplot() +
  
  # Campo
  annotate("rect",xmin = 0, xmax = 120, ymin = 0, ymax = 80, fill = NA, colour = "black", size = 0.6) +
  annotate("rect",xmin = 0, xmax = 60, ymin = 0, ymax = 80, fill = NA, colour = "black", size = 0.6) +
  annotate("rect",xmin = 18, xmax = 0, ymin = 18, ymax = 62, fill = NA, colour = "black", size = 0.6) +
  annotate("rect",xmin = 102, xmax = 120, ymin = 18, ymax = 62, fill = NA, colour = "black", size = 0.6) +
  annotate("rect",xmin = 0, xmax = 6, ymin = 30, ymax = 50, fill = NA, colour = "black", size = 0.6) +
  annotate("rect",xmin = 120, xmax = 114, ymin = 30, ymax = 50, fill = NA, colour = "black", size = 0.6) +
  annotate("rect",xmin = 120, xmax = 120.5, ymin =36, ymax = 44, fill = NA, colour = "black", size = 0.6) +
  annotate("rect",xmin = 0, xmax = -0.5, ymin =36, ymax = 44, fill = NA, colour = "black", size = 0.6) +
  annotate("segment", x = 60, xend = 60, y = -0.5, yend = 80.5, colour = "black", size = 0.6)+
  annotate("segment", x = 0, xend = 0, y = 0, yend = 80, colour = "black", size = 0.6)+
  annotate("segment", x = 120, xend = 120, y = 0, yend = 80, colour = "black", size = 0.6)+
  theme(rect = element_blank(),
        line = element_blank()) +
  # add penalty spot right
  annotate("point", x = 108 , y = 40, colour = "black", size = 1.05) +
  annotate("path", colour = "black", size = 0.6,
           x=60+10*cos(seq(0,2*pi,length.out=2000)),
           y=40+10*sin(seq(0,2*pi,length.out=2000)))+
  # add centre spot
  annotate("point", x = 60 , y = 40, colour = "black", size = 1.05) +
  annotate("path", x=12+10*cos(seq(-0.3*pi,0.3*pi,length.out=30)), size = 0.6,
           y=40+10*sin(seq(-0.3*pi,0.3*pi,length.out=30)), col="black") +
  annotate("path", x=107.84-10*cos(seq(-0.3*pi,0.3*pi,length.out=30)), size = 0.6,
           y=40-10*sin(seq(-0.3*pi,0.3*pi,length.out=30)), col="black") +
  
  # Chutes
  geom_point(data = shots_sau, aes(x = location.x, y = location.y, fill = shot.statsbomb_xg, shape = shot.body_part.name),
             size = 6, alpha = 0.8) + #3

    # Tema
  theme(axis.text.x=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.caption=element_text(size=13,family="Source Sans Pro", hjust=0.5, vjust=0.5),
        plot.subtitle = element_text(size = 18, family="Source Sans Pro", hjust = 0.5),
        axis.text.y=element_blank(),
        legend.position = "top",
        legend.title=element_text(size=12,family="Source Sans Pro"),
        legend.text=element_text(size=11,family="Source Sans Pro"),
        legend.spacing.x = unit(0, 'cm'),  # Reduz o espaço entre as legendas
        legend.margin = margin(c(20, 5, -35, 30)),
        legend.key.size = unit(0.7, "cm"),
        plot.title = element_text(margin = margin(r = 10, b = 10), size = 18, family="Source Sans Pro", colour = "black", hjust = 0.5),
        legend.direction = "horizontal",
        axis.ticks=element_blank(),
        aspect.ratio = c(50/100),
        plot.background = element_rect(fill = "white"),
        strip.text.x = element_text(size=10, family="Source Sans Pro")) +
  labs(title = "Mapa de Chutes da Árabia Saudita") +
  scale_shape_manual(values = c("Head" = 21, "Right Foot" = 25, "Left Foot" = 24, "Other" = 23),
                     labels = c("Head" = "Cabeça", "Right Foot" = "Pé Direito", "Left Foot" = "Pé Esquerdo", "Other" = "Outro"), 
                     name ="") + 
  scale_fill_gradientn(colours = shotmapxgcolors, limit = c(0, 0.8), oob=scales::squish, name = "Gols Esperados") + 
  # Configuração das legendas (orientação e posicionamento)
  guides(fill = guide_colourbar(title.position = "top"),  # Escala de cores no topo
         shape = guide_legend(override.aes = list(size = 5, fill = "black"), 
                              title.position = "bottom")) +  # Formas embaixo
  coord_flip(xlim = c(80, 125)) #8

shot_plot_sau

```

<br>

### Passes

<br>

```{r, echo=FALSE, message=FALSE, warning=FALSE}

# Passes no último terço
roll_final_pass <- events %>%
  mutate(location.x = map_dbl(location, 1, .default = NA),
         location.y = map_dbl(location, 2, .default = NA),
         pass.end_location.x = map_dbl(pass.end_location, 1, .default = NA),
         pass.end_location.y = map_dbl(pass.end_location, 2, .default = NA)) %>%
  group_by(team.name, minute) %>%
  mutate(count = case_when(
    type.name == "Pass" & location.x >= 80 ~ 1L,
    TRUE ~ 0L
  )) %>%
  select(team.name, minute, count) %>%
  ungroup()

# Metricas
first_min <- events$minute %>% unique() %>% first()
last_min <- events$minute %>% unique() %>% last()
minute <- c(first_min:last_min)
team.name <- c("Argentina", "Saudi Arabia")
# crossing(minute, team.name) %>% slice(26:32)

rolling_sum <- tibbletime::rollify(.f = sum, window = 5)
roll_pass <- crossing(minute, team.name) %>%
  left_join(roll_final_pass, by = c("minute", "team.name")) %>%
  group_by(team.name, minute) %>%
  summarize_all(sum) %>%
  ungroup() %>%
  mutate(count = ifelse(is.na(count), 0, count)) %>%
  group_by(team.name) %>%
  mutate(rollsum = rolling_sum(count),
         rollsum = ifelse(is.na(rollsum), 0, rollsum)) %>%
  group_by(team.name) %>%
  select(-count) %>%
  filter(row_number() %% 5 == 1 | row_number() == n())

```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.height=5}

# Gráfico
finalthird_rollingplot <- roll_pass %>%
  ggplot(aes(x = minute, y = rollsum,
             group = team.name)) +
  geom_line(data = roll_pass,
            size = 1) +
  geom_point(data = roll_pass,
             aes(fill = team.name),
             size = 3, shape = 21, stroke = 1.5) +
  scale_x_continuous(breaks = c(seq(0, 90, by = 5), 104),
                     labels = c(seq(0, 40, by = 5), "HT", 
                                seq(50, 90, by = 5), "FT"),
                     expand = c(0.01, 0),
                     limits = c(0, 104)) +
  scale_y_continuous(breaks = seq(0, 30, by = 5),
                     labels = seq(0, 30, by = 5)) +
  scale_fill_manual(values = c("Argentina" = "#00CED1",
                               "Saudi Arabia" = "#006400")) +
  scale_color_manual(values = c("Argentina" = "#00CED1",
                                "Saudi Arabia" = "#006400"),
                     labels = c("Argentina", "Árabia Saudita")) +
  labs(title = "Evolução da Frequência de Passes no Terço Final",
       x = NULL,
       y = "Passes no Último Terço") +
  theme_minimal() +
  theme(text = element_text(family = "Source Sans Pro"),
        plot.title = element_markdown(size = 18, family = "Source Sans Pro"),
        axis.title = element_text(size = 12, color = "grey20"),
        axis.text = element_text(size = 8, face = "bold"),
        panel.grid.minor = element_blank(),
        legend.text = element_markdown(size = 14),
        legend.position = c(0.25, 0.95),
        legend.direction = "horizontal",
        legend.title = element_blank())

finalthird_rollingplot

```

<br>

```{r, echo=FALSE, warning=FALSE, message=FALSE}

# Passes - Contando faltas, escanteios, ...
passes_arg = events %>%
  filter(type.name=="Pass" & is.na(pass.outcome.name) & team.name == 'Argentina') %>% 
  mutate(location.x = map_dbl(location, 1),
         location.y = map_dbl(location, 2),
         pass.end_location.x = map_dbl(pass.end_location, 1),
         pass.end_location.y = map_dbl(pass.end_location, 2)) %>% 
  filter(pass.end_location.x>=102 & pass.end_location.y<=62 & pass.end_location.y>=18)

passes_sau = events %>%
  filter(type.name=="Pass" & is.na(pass.outcome.name) & team.name == 'Saudi Arabia') %>% 
  mutate(location.x = map_dbl(location, 1),
         location.y = map_dbl(location, 2),
         pass.end_location.x = map_dbl(pass.end_location, 1),
         pass.end_location.y = map_dbl(pass.end_location, 2)) %>% 
  filter(pass.end_location.x>=102 & pass.end_location.y<=62 & pass.end_location.y>=18) %>%
  mutate(location.x = 120 - location.x,
         location.y = 80 - location.y,
         pass.end_location.x = 120 - pass.end_location.x,
         pass.end_location.y = 80 - pass.end_location.y)

create_Pitch(
  grass_colour = "#538032", 
  line_colour =  "#ffffff", 
  background_colour = "#538032", 
  goal_colour = "#000000"
  ) +
  geom_segment(data = passes_arg, aes(x = location.x, y = location.y,
                                  xend = pass.end_location.x, yend = pass.end_location.y),
               lineend = "round", linewidth = 0.5, colour = "#00CED1", arrow =
                 arrow(length = unit(0.07, "inches"), ends = "last", type = "open")) +
  geom_segment(data = passes_sau, aes(x = location.x, y = location.y,
                                  xend = pass.end_location.x, yend = pass.end_location.y),
               lineend = "round", linewidth = 0.5, colour = "#006400", arrow =
                 arrow(length = unit(0.07, "inches"), ends = "last", type = "open")) +
  geom_text(aes(x = 85, y = 85, label = glue('Argentina: {nrow(passes_arg)}')), size = 5, colour = "#00CED1") +
  geom_text(aes(x = 30, y = 85, label = glue('Árabia Saudita: {nrow(passes_sau)}')), size = 5, colour = "white") +
  labs(title = "Passes Completados para a Grande Área") +
  coord_fixed(ratio = 105/100) +
  theme(text = element_text(family = "Source Sans Pro"),
        plot.title = element_markdown(size = 18, family = "Source Sans Pro"),
        panel.grid.minor = element_blank(),
        legend.direction = "horizontal",
        legend.title = element_blank())

```

<br>

```{r, echo=FALSE, warning=FALSE, message=FALSE}

# Passes Connection
pass_box_arg <- events %>%
  mutate(pass.outcome.name = fct_explicit_na(pass.outcome.name, "Complete")) %>%
  mutate(location.x = map_dbl(location, 1, .default = NA),
         location.y = map_dbl(location, 2, .default = NA),
         pass.end_location.x = map_dbl(pass.end_location, 1, .default = NA),
         pass.end_location.y = map_dbl(pass.end_location, 2, .default = NA)) %>% 
  filter(type.name == "Pass",
         pass.outcome.name == "Complete",
         pass.end_location.x >= 102 & pass.end_location.y <= 62 &
           pass.end_location.y >= 18) %>%
  select(player.name, pass.recipient.name,
         position.name, position.id,
         location.x, location.y,
         pass.end_location.x, pass.end_location.y,
         contains("pass")) %>%
  add_count(player.name, name = "did_pass") %>%
  add_count(pass.recipient.name, name = "received_pass") 

aux1 = pass_box_arg[, c('player.name', 'did_pass')] %>%
  distinct() %>%
  arrange(desc(did_pass))

aux2 = pass_box_arg[, c('pass.recipient.name', 'received_pass')] %>%
  distinct() %>%
  arrange(desc(received_pass))

# Passes para dentro da área
aux = cbind(head(aux1, 5), head(aux2, 5))
colnames(aux) = c('Fez', 'n', 'Recebeu', 'n')
titulo = 'Quem Fez x Quem Recebeu'

tabela_kable1 <- kable(aux, 
                     caption = titulo,
                     format = "html",
                     digits = 2, align = 'c') 

# Adicionar estilos com kableExtra
tabela_kable1 <- tabela_kable1 %>%
  kable_styling("striped", full_width = T) %>%
  kable_styling(position = "center")  # Centralizando a tabela

tabela_kable1
```

<br>
<br>

## Ações Sem Bola

<br>


```{r, echo=FALSE, message=FALSE, warning=FALSE}


# ----------- Heatmaps --------- #

heatmap = events %>%
  mutate( 
        location.x = map_dbl(location, 1, .default=NA),
        location.y = map_dbl(location, 2, .default=NA),
        
        # Separa os Locais 
        location.x = ifelse(location.x>120, 120, location.x),
        location.y = ifelse(location.y>80, 80, location.y),
        location.x = ifelse(location.x<0, 0, location.x),
        location.y = ifelse(location.y<0, 0, location.y))

heatmap$xbin <- cut(heatmap$location.x, breaks = seq(from=0, to=120, by = 20),include.lowest=TRUE )
heatmap$ybin <- cut(heatmap$location.y, breaks = seq(from=0, to=80, by = 20),include.lowest=TRUE)


#########################################################################################################

# ----------- Defensive --------- #

defensive = heatmap %>%
  filter(type.name=="Pressure" | duel.type.name=="Tackle" |
           type.name=="Foul Committed" | type.name=="Interception" |
           type.name=="Block" | type.name=='Ball Recovery') %>%
  group_by(team.name, type.name) %>%
  summarise(total = n())


# Tabela

df_wide <- defensive %>%
  pivot_wider(names_from = type.name, values_from = total)

colnames(df_wide) = c('Time', colnames(df_wide)[2:length(colnames(df_wide))])

titulo = "Número de Ações Defensivas Realizadas"

tabela_kable <- kable(df_wide, 
                     caption = titulo,
                     format = "html",
                     digits = 2, align = 'c') 

# Adicionar estilos com kableExtra
tabela_kable <- tabela_kable %>%
  kable_styling("striped", full_width = T) %>%
  kable_styling(position = "center")  # Centralizando a tabela

tabela_kable
```

<br>

```{r, echo=FALSE, message=FALSE, warning=FALSE}

# ----------- Defensive Actions --------- #

# DA totais da partida
defensive_actions_total = heatmap %>%
  filter(duel.type.name=="Tackle" | type.name=="Foul Committed" | type.name=='Ball Recovery' |
           type.name=="Interception" | type.name=="Block" | type.name=='Pressure') %>%
  group_by(team.name) %>%
  mutate(total_DA = n()) %>%
  group_by(team.name, xbin, ybin) %>%
  summarise(total_DA = max(total_DA),
            bin_DA = n(),
            bin_pct = bin_DA/total_DA,
            location.x = median(location.x),
            location.y = median(location.y)) %>%
  group_by(xbin, ybin) %>%
  group_by(team.name, xbin, ybin) %>%
  mutate(period = 0)

# Dividido por Tempos
defensive_actions_halfs = heatmap %>%
  filter(duel.type.name=="Tackle" | type.name=="Foul Committed" | type.name=='Ball Recovery' |
           type.name=="Interception" | type.name=="Block" | type.name=='Pressure') %>%
  group_by(team.name, period) %>%
  mutate(total_DA = n()) %>%
  group_by(team.name, period, xbin, ybin) %>%
  summarise(total_DA = max(total_DA),
            bin_DA = n(),
            bin_pct = bin_DA/total_DA,
            location.x = median(location.x),
            location.y = median(location.y)) %>%
  group_by(xbin, ybin) %>%
  group_by(team.name, period, xbin, ybin)

# Junta
defensive_actions = rbind(defensive_actions_total, defensive_actions_halfs)
defensive_actions = defensive_actions %>%
  mutate(period = ifelse(period==0, "90'", 
                         ifelse(period==1, "First Half", 'Second Half')))

# Colors
defensive_colors <- c("#660000", "#e60000", "#ff9999", "#ffe6e6", "#cdd2d6")
# defensive_colors <- c("#dc2429", "#dc2329", "#df272d", "#df3238", "#e14348", "#e44d51",
#                       "#e35256", "#e76266", "#e9777b", "#ec8589", "#ec898d", "#ef9195",
#                       "#ef9ea1", "#f0a6a9", "#f2abae", "#f4b9bc", "#f8d1d2", "#f9e0e2",
#                       "#f7e1e3", "#f5e2e4", "#d4d5d8", "#d1d3d8", "#cdd2d6", "#c8cdd3", "#c0c7cd",
#                       "#b9c0c8", "#b5bcc3", "#909ba5", "#8f9aa5", "#818c98", "#798590",
#                       "#697785", "#526173", "#435367", "#3a4b60", "#2e4257", "#1d3048",
#                       "#11263e", "#11273e", "#0d233a", "#020c16")


# Plot
ggplot(data= defensive_actions, aes(x = location.x, y = location.y, fill = bin_pct, group =bin_pct)) +
  geom_bin2d(binwidth = c(20, 20), position = "identity", alpha = 0.9) + #2
  annotate("rect",xmin = 0, xmax = 120, ymin = 0, ymax = 80, fill = NA, colour = "black", size = 0.6) +
  annotate("rect",xmin = 0, xmax = 60, ymin = 0, ymax = 80, fill = NA, colour = "black", size = 0.6) +
  annotate("rect",xmin = 18, xmax = 0, ymin = 18, ymax = 62, fill = NA, colour = "white", size = 0.6) +
  annotate("rect",xmin = 102, xmax = 120, ymin = 18, ymax = 62, fill = NA, colour = "white", size = 0.6) +
  annotate("rect",xmin = 0, xmax = 6, ymin = 30, ymax = 50, fill = NA, colour = "white", size = 0.6) +
  annotate("rect",xmin = 120, xmax = 114, ymin = 30, ymax = 50, fill = NA, colour = "white", size = 0.6) +
  annotate("rect",xmin = 120, xmax = 120.5, ymin =36, ymax = 44, fill = NA, colour = "black", size = 0.6) +
  annotate("rect",xmin = 0, xmax = -0.5, ymin =36, ymax = 44, fill = NA, colour = "black", size = 0.6) +
  annotate("segment", x = 60, xend = 60, y = -0.5, yend = 80.5, colour = "white", size = 0.6)+
  annotate("segment", x = 0, xend = 0, y = 0, yend = 80, colour = "black", size = 0.6)+
  annotate("segment", x = 120, xend = 120, y = 0, yend = 80, colour = "black", size = 0.6)+
  theme(rect = element_blank(),
        line = element_blank()) +
  annotate("point", x = 12 , y = 40, colour = "white", size = 1.05) +
  annotate("point", x = 108 , y = 40, colour = "white", size = 1.05) +
  annotate("path", colour = "white", size = 0.6,
           x=60+10*cos(seq(0,2*pi,length.out=2000)),
           y=40+10*sin(seq(0,2*pi,length.out=2000)))+
  annotate("point", x = 60 , y = 40, colour = "white", size = 1.05) +
  annotate("path", x=12+10*cos(seq(-0.3*pi,0.3*pi,length.out=30)), size = 0.6,
           y=40+10*sin(seq(-0.3*pi,0.3*pi,length.out=30)), col="white") +
  annotate("path", x=108-10*cos(seq(-0.3*pi,0.3*pi,length.out=30)), size = 0.6,
           y=40-10*sin(seq(-0.3*pi,0.3*pi,length.out=30)), col="white") +
  
  # Tema
  theme(axis.text.x=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.caption=element_text(size=16,family="Source Sans Pro", hjust=0.5, vjust=0.5),
        plot.subtitle = element_text(size = 10, family="Source Sans Pro", hjust = 0.5),
        axis.text.y=element_blank(),
        legend.title = element_blank(),
        legend.text=element_text(size=10,family="Source Sans Pro"),
        legend.key.size = unit(1.5, "cm"),
        plot.title = element_text(margin = margin(r = 10, b = 10), size = 18,
                                  family="Source Sans Pro", colour = "black", hjust = 0.5),
        legend.direction = "vertical",
        axis.ticks=element_blank(),
        panel.background = element_rect(fill = "#538032", colour = NA),
        plot.background = element_rect(fill = "white"),
        strip.text.x = element_text(size=10, family="Source Sans Pro")) +
  scale_y_reverse() + 
  scale_fill_gradientn(colours = defensive_colors, trans = "reverse", labels =
                         scales::percent_format(accuracy = 1), limits = c(0.1, 0)) +
  labs(title = "Ações Defensivas", subtitle = "Tackle, Foul Committed, Ball Recovery, Interception, Block e Pressure \n") +
  coord_fixed(ratio = 95/100) +
  
  annotation_custom(grob = linesGrob(arrow=arrow(type="open", ends="last",
                                                 length=unit(2.55,"mm")), gp=gpar(col="black", fill=NA, lwd=2.2)),
                    xmin=25, xmax = 95, ymin = -83, ymax = -83) + #9
  facet_wrap(~team.name+period)+ 
  guides(fill = guide_legend(reverse = TRUE)) 

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}

# ----------- Pressure Actions --------- #

# Pressure totais da partida
pressure_total = heatmap %>%
  filter(type.name=='Pressure') %>%
  group_by(team.name) %>%
  mutate(total_DA = n()) %>%
  group_by(team.name, xbin, ybin) %>%
  summarise(total_DA = max(total_DA),
            bin_DA = n(),
            bin_pct = bin_DA/total_DA,
            location.x = median(location.x),
            location.y = median(location.y)) %>%
  group_by(xbin, ybin) %>%
  group_by(team.name, xbin, ybin) %>%
  mutate(period = 0)

# Dividido por Tempos
pressure_halfs = heatmap %>%
  filter(type.name=='Pressure') %>%
  group_by(team.name, period) %>%
  mutate(total_DA = n()) %>%
  group_by(team.name, period, xbin, ybin) %>%
  summarise(total_DA = max(total_DA),
            bin_DA = n(),
            bin_pct = bin_DA/total_DA,
            location.x = median(location.x),
            location.y = median(location.y)) %>%
  group_by(xbin, ybin) %>%
  group_by(team.name, period, xbin, ybin)

# Junta
pressure = rbind(pressure_total, pressure_halfs)
pressure = pressure %>%
  mutate(period = ifelse(period==0, "90'", 
                         ifelse(period==1, "First Half", 'Second Half')))

# Plot
ggplot(data= pressure, aes(x = location.x, y = location.y, fill = bin_pct, group =bin_pct)) +
  geom_bin2d(binwidth = c(20, 20), position = "identity", alpha = 0.9) + #2
  annotate("rect",xmin = 0, xmax = 120, ymin = 0, ymax = 80, fill = NA, colour = "black", size = 0.6) +
  annotate("rect",xmin = 0, xmax = 60, ymin = 0, ymax = 80, fill = NA, colour = "black", size = 0.6) +
  annotate("rect",xmin = 18, xmax = 0, ymin = 18, ymax = 62, fill = NA, colour = "white", size = 0.6) +
  annotate("rect",xmin = 102, xmax = 120, ymin = 18, ymax = 62, fill = NA, colour = "white", size = 0.6) +
  annotate("rect",xmin = 0, xmax = 6, ymin = 30, ymax = 50, fill = NA, colour = "white", size = 0.6) +
  annotate("rect",xmin = 120, xmax = 114, ymin = 30, ymax = 50, fill = NA, colour = "white", size = 0.6) +
  annotate("rect",xmin = 120, xmax = 120.5, ymin =36, ymax = 44, fill = NA, colour = "black", size = 0.6) +
  annotate("rect",xmin = 0, xmax = -0.5, ymin =36, ymax = 44, fill = NA, colour = "black", size = 0.6) +
  annotate("segment", x = 60, xend = 60, y = -0.5, yend = 80.5, colour = "white", size = 0.6)+
  annotate("segment", x = 0, xend = 0, y = 0, yend = 80, colour = "black", size = 0.6)+
  annotate("segment", x = 120, xend = 120, y = 0, yend = 80, colour = "black", size = 0.6)+
  theme(rect = element_blank(),
        line = element_blank()) +
  annotate("point", x = 12 , y = 40, colour = "white", size = 1.05) +
  annotate("point", x = 108 , y = 40, colour = "white", size = 1.05) +
  annotate("path", colour = "white", size = 0.6,
           x=60+10*cos(seq(0,2*pi,length.out=2000)),
           y=40+10*sin(seq(0,2*pi,length.out=2000)))+
  annotate("point", x = 60 , y = 40, colour = "white", size = 1.05) +
  annotate("path", x=12+10*cos(seq(-0.3*pi,0.3*pi,length.out=30)), size = 0.6,
           y=40+10*sin(seq(-0.3*pi,0.3*pi,length.out=30)), col="white") +
  annotate("path", x=108-10*cos(seq(-0.3*pi,0.3*pi,length.out=30)), size = 0.6,
           y=40-10*sin(seq(-0.3*pi,0.3*pi,length.out=30)), col="white") +
  
  # Tema
  theme(axis.text.x=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.caption=element_text(size=16,family="Source Sans Pro", hjust=0.5, vjust=0.5),
        plot.subtitle = element_text(size = 14, family="Source Sans Pro", hjust = 0.5),
        axis.text.y=element_blank(),
        legend.title = element_blank(),
        legend.text=element_text(size=10,family="Source Sans Pro"),
        legend.key.size = unit(1.5, "cm"),
        plot.title = element_text(margin = margin(r = 10, b = 10), size = 18,
                                  family="Source Sans Pro", colour = "black", hjust = 0.5),
        legend.direction = "vertical",
        axis.ticks=element_blank(),
        panel.background = element_rect(fill = "#538032", colour = NA),
        plot.background = element_rect(fill = "white"),
        strip.text.x = element_text(size=10,family="Source Sans Pro")) +
  scale_y_reverse() + 
  scale_fill_gradientn(colours = defensive_colors, trans = "reverse", 
                       labels = scales::percent_format(accuracy = 1), limits = c(0.1, 0)) +
  coord_fixed(ratio = 95/100) +
  labs(title = "Eventos de Pressão") +
  annotation_custom(grob = linesGrob(arrow=arrow(type="open", ends="last",
                                                 length=unit(2.55,"mm")), gp=gpar(col="black", fill=NA, lwd=2.2)),
                    xmin=25, xmax = 95, ymin = -83, ymax = -83) + #9
  facet_wrap(~team.name+period)+ 
  guides(fill = guide_legend(reverse = TRUE)) 
```


<br>